In [1]:
import numpy as np

a = 2*np.eye(3, 4, 0)+np.eye(3, 4, 1)
print(a)

[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


In [11]:
mat = a
print(mat.reshape(12,1))

[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]


In [9]:
x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)

try:
    n = np.dot(X, Y.T)
    print(n)
except:
    print("matrix shapes do not match")

2 3
8 7 7 14 4 6
4 3
5 5 1 5 2 6 3 3 9 1 4 6
[[ 82  96 108  78]
 [ 96 114 108  66]]


In [8]:
n = np.dot(X, Y.T)
print(n)

[[ 82  96 108  78]
 [ 96 114 108  66]]
