In [1]:
import numpy as np

a = 2*np.eye(3, 4, 0)+np.eye(3, 4, 1)
print(a)

[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


In [11]:
mat = a
print(mat.reshape(12,1))

[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]


In [9]:
x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)

try:
    n = np.dot(X, Y.T)
    print(n)
except:
    print("matrix shapes do not match")

2 3
8 7 7 14 4 6
4 3
5 5 1 5 2 6 3 3 9 1 4 6
[[ 82  96 108  78]
 [ 96 114 108  66]]


In [8]:
n = np.dot(X, Y.T)
print(n)

[[ 82  96 108  78]
 [ 96 114 108  66]]


In [7]:
# 1.7 Линейная алгебра в деле. Exercise 3
# посчитайте сумму квадратов отклонений и сумму модулей отклонений. В ответе напишите максимальное из этих двух значений

arr = ((0.25, 0), (0.5, 1), (0.75, 0), (1.25, 0), (1.75, 1), (2,2))

def func(x):
    return 2*x-1

sum_sq, sum_abs =0, 0

for a in arr:
    sum_sq += (func(a[0]) - a[1])**2
    sum_abs += abs(func(a[0]) - a[1])
    
print('сумма квадратов отклонений', sum_sq)
print('сумма модулей отклонений', sum_abs)
print('Итоговый ответ', max(sum_sq,sum_abs))

сумма квадратов отклонений 7.0
сумма модулей отклонений 6.0
Итоговый ответ 7.0


In [1]:
# 1.7 Линейная алгебра в деле. Exercise 3
# чужая реализация предыдущей задачи с другим форматом входных данных (y и y^)
arr = ((0, -0.5), (1, 0), (0, 0.5), (0, 1.5), (1, 2.5), (2,3))

def sqerr(a, b):
  return (a - b)**2

def abserr(a, b):
  return abs(a - b)

def errsum(err_fun):
  return sum(list(map(lambda pair: err_fun(pair[0], pair[1]), arr)))

print(str(max(errsum(abserr), errsum(sqerr))))

print(errsum(abserr), errsum(sqerr))

7.0
6.0 7.0


In [12]:
# 1.7 Линейная алгебра в деле. Exercise 5

import numpy as np
from numpy.linalg import inv

y = np.array(((10,), (7,), (12,)))
x = np.array(((1,60),(1,50),(1,75)))
B = np.dot(np.dot(inv(np.dot(x.T,x)), x.T), y)
print(*np.round(B,3))

[-2.342] [0.195]


In [21]:
# 1.7 Линейная алгебра в деле. Exercise 7
#Найдите оптимальные коэффициенты для построения линейной регрессии.
#На вход вашему решению будет подано название csv-файла, из которого нужно считать данные. 

import urllib
from urllib import request
import numpy as np
from numpy.linalg import inv

fname = input()  # read file name from stdin
#fname = r'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'
f = urllib.request.urlopen(fname)  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with
y = data[:, 0]
x = data[:, 1:]
#print (x.shape)

one = np.ones((len(x),1))
#print(one.shape)
x = np.concatenate((one, x), axis=1 )
#print(x.shape)

B = np.dot(np.dot(inv(np.dot(x.T,x)), x.T), y)
print(*np.round(B,4))


-3.6558 -0.2164 0.0737 4.4125 -25.4684 7.1432 -1.3011


In [ ]:
#2.7 Однослойные модели. Exercise 1

import numpy as np

def vectorized_forward_pass(self, input_matrix):        
    # your code goes here


In [12]:
#3.4 Целевые функции. Exercise 1 
# Посчитайте значение квадратичной целевой функции и целевой функции cross entropy. 
import math

y_hat = [1, 0.3, 0.1]
y = [1,0,0]
cross_entropy, square = 0,0
for y_hat_i, y_i in zip(y_hat,y):
    square += (y_i-y_hat_i)**2
    try:
        cross_entropy += (y_i*math.log(y_hat_i) + (1-y_i)*math.log(1-y_hat_i) )
    except:
        print('Математическая ошибка. Значение операндов: y=', y_i, ', y_hat=', y_hat_i, ', 1-y_i=', 1-y_i, \
              ', 1-y_hat_i=', 1-y_hat_i )
        
square /= len(y)
cross_entropy /= -len(y)
    
print(round(square,3), round(cross_entropy,3))

Математическая ошибка. Значение операндов: y= 1 , y_hat= 1 , 1-y_i= 0 , 1-y_hat_i= 0
0.033 0.154
